# Generated by Django 4.0.2 on 2022-02-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='Unblock', max_length=20),
        ),
    ]
